### PR TITLE
Fix minor spelling mistakes

### PR DESCRIPTION
**Pull request by realsobek**

### CODE REVIEW

**Comment by realsobek** [comment]
There is a mix of British English and American English, f.e.:
- behaviour
- colour
- Initialise
- licence
- LicenseInfo
- synchronisation , synchronise
- optimisations

Any opinion about that?

**Comment by derfian** [comment]
Nice work!

My personal opinion is that we should try to stick to one of the English variants.

**Comment by hean01-cendio** [comment]
I would also prefer American English. However, before we agree upon that, we should verify that American English is used in the Microsoft RDP specifications.

**Comment by hean01-cendio** [comment]
I have created an issue #188 for the inconsistent use of American and British English.

@realsobek Could you please fix the conflict and I will merge this PR

**Comment by realsobek** [comment]
@hean01-cendio the conflict has been resolved; note: in 'rdesktop.c' I added the offset placement to the '-g' option

**Comment by hean01-cendio** [comment]
Thanks for you great work!

**Pull request merged**
