### PR TITLE
Add option to omit password prompt

### PR DESCRIPTION
**Pull request by nospam3159**
Fix issue #191

Regression introduced by commit 1aaafc8.

### CODE REVIEW

**Comment by trentasis** [comment]
Very interesting to recover thi feature that was available with previous version, in thinclient envjronment without this you can't use rdesktop

Thanks

**Comment by gilbsfr24** [comment]
I agree, it is not necessary to add new parameters, it causes an upward compatibility break

**Comment by trentasis** [comment]
Anybody can give a real example how to login to multiple windows 2012 without to enter two times the password?

Thanks

**Comment by hean01-cendio** [comment]
Commit bc727e7 makes it possible to provide an empty password via -p argument that will set aside the password prompt and take the end user to remote login page.

**Pull request closed without merging**
