### PR TITLE
Add support for pulseaudio backend

### PR DESCRIPTION
**Pull request by hean01-cendio**
This work is done by Nikita Krupenko which sent a patch to
rdesktop in 2010 for version 1.6.0. I have now ported it
over to trunk and it seems to work as expected.

### CODE REVIEW

**Comment by uglym8** [comment]
Just verified with **W10Ultimate** and **-r sound:local:pulse**.
Checked with Youtube.
Seems to work fine.

**Comment by uglym8** [comment]
BTW, what's preventing the merging of this PR?

**Comment by alexandrevicenzi** [comment]
I get `Sound(error): oss_open(), open() failed: No such file or directory` even if I apply this patch.

**Comment by alexandrevicenzi** [comment]
Nevermind, I think I did something wrong. It's working with this patch applied. :)

Tested with Windows 7 Pro.

**Comment by uglym8** [comment]
@alexandrevicenzi, thank you for testing this.

**Comment by hean01-cendio** [comment]
@alexandrevicenzi @uglym8 nice that we got another test of this PR, lets merge it.

**Comment by kekePower** [comment]
Another thing.

Even though I've enabled Pulseaudio during configure, rdesktop --help shows only libao available.

         '-r sound:[local[:driver[:device]]|off|remote]': enable sound redirection
                     remote would leave sound on server
                     available drivers for 'local':
                     libao:     libao output driver, default device: system dependent

**Comment by uglym8** [comment]
Hi!

What version are you trying to build?
The latest?
I've just verified this build on ArchLinux and it builds just fine.
-----snip----
````bash
checking for ao... yes
checking for libpulse... yes
checking for alsa... yes
checking for samplerate... yes
````

Makefile contents (line number 20):
````
LDFLAGS     =  -L/usr/lib -L/usr/lib64 -lssl -lcrypto -ldl  -lgssapi_krb5 -lXrandr -lXcursor -lpcsclite -lsamplerate -lasound -lpulse -lao
`````
````
 '-r sound:[local[:driver[:device]]|off|remote]': enable sound redirection
                     remote would leave sound on server
                     available drivers for 'local':
                     pulse:     PulseAudio output driver, default device: system dependent
                     alsa:      ALSA output driver, default device: default
                     oss:       OSS output driver, default device: /dev/dsp or $AUDIODEV
                     libao:     libao output driver, default device: system dependent
````

Is Mageia using pacman too?

````
$ pacman -Ss pulse|grep install
extra/libao 1.2.2-1 [installed]
extra/libcanberra-pulse 0.30+2+gc0620e4-1 [installed]
extra/libpulse 11.1-1 [installed]
extra/pavucontrol 3.0-4 [installed]
extra/pulseaudio 11.1-1 [installed]
````

**Comment by kekePower** [comment]
Hi.

The problem appears to be with Firefox as the sound was sent to Pulseaudio with Chrome. I have NO idea why Firefox won't send any audio...

My line 20 in Makefile:
  LDFLAGS     =  -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -lgmp  -lgssapi_krb5 -lXrandr -lXcursor -ltasn1 -lnettle -lhogweed -lgnutls -lpcsclite -lsamplerate-lasound -lpulse -lao   -L/usr/lib64

I also removed --with-sound=pulse during configure and the same output as you do in rdesktop --help.
         '-r sound:[local[:driver[:device]]|off|remote]': enable sound redirection
                     remote would leave sound on server
                     available drivers for 'local':
                     pulse:     PulseAudio output driver, default device: system dependent
                     alsa:      ALSA output driver, default device: default
                     oss:       OSS output driver, default device: /dev/dsp or $AUDIODEV
                     libao:     libao output driver, default device: system dependent

**Comment by kekePower** [comment]
`$ rpm -qa | grep pulseaudio
pulseaudio-module-zeroconf-11.1-1.intelsb.mga6
pulseaudio-utils-11.1-1.intelsb.mga6
pulseaudio-client-config-11.1-1.intelsb.mga6
lib64alsa-plugins-pulseaudio-1.1.4-1.mga6
libpulseaudio0-10.0-1.1.mga6
lib64pulseaudio0-11.1-1.intelsb.mga6
lib64pulseaudio-devel-11.1-1.intelsb.mga6
pulseaudio-module-x11-11.1-1.intelsb.mga6
pulseaudio-11.1-1.intelsb.mga6
task-pulseaudio-2011.0-8.mga6
pulseaudio-module-gconf-11.1-1.intelsb.mga6
libalsa-plugins-pulseaudio-1.1.4-1.mga6`

**Pull request merged**
