### PR TITLE
Increase maximum password length, and other fixes.

### LINKED ISSUE #144: Increase maximum password length
Because certain three-letter agencies have demonstrated an ability to crack 32-character passwords in real-time, my employer has mandated that all passwords be a minimum of 64 randomly-generated characters.  When I set a 64-character password for Windows, I could no longer log in via rdesktop.  Some investigation revealed a hard-coded 63-byte password length limitation, as the character array is declared with length 64, including the null-byte terminator.

Windows supports passwords of up to 256 bytes (128 wide-byte characters), so rdesktop ought to do the same.

It would be better yet to support 256 bytes *by default*, and allow the limit to be increased or decreased via compilation switches.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/49178263-increase-maximum-password-length?utm_campaign=plugin&utm_content=tracker%2F19353203&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F19353203&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by pillarsdotnet**
* Resolves #144 by setting maximum host, password, and file path length via autoconf defines.
* Fixes a minor spelling error in the manpage.
* Uses [fputs](https://linux.die.net/man/3/fputs) instead of [fprintf](https://linux.die.net/man/3/fprintf) where there is no format string.

### CODE REVIEW

**Comment by pillarsdotnet** [comment]
@hean01-cendio -- Can I get a review of this?

**Comment by hean01-cendio** [comment]
I have already reviewed the code. One thing only, did you verify that the protocol were the strings are used is dynamic lengthed strings ?

**Comment by CendioOssman** [comment]
It seems like overkill (or even possible foot shooting) to have these configurable. Can't we just adjust these to the protocol/system limitations and be done with it? `HOST_NAME_MAX` and `PATH_MAX` should both come from `limits.h` and shouldn't require special handling at all.

**Comment by hean01-cendio** [comment]
I'm closing this pull request due to it's the wrong take on the problem, also it includes unrelated changes. Added more information on issue #144.

**Pull request closed without merging**
